const assert=require('node:assert/strict');
const fs=require('fs');
const path=require('path');
const {createFixture}=require('./fixture.cjs');
const {parseResponse,identifiers}=require('../sim-parser');
(async()=>{
  const fixture=await createFixture();const {request,workspace,origin}=fixture;
  try {
    assert.equal((await fetch(origin+'/api/workspace/mail')).status,401);
    let result=await request('/api/workspace/mail');const id=result.data.messages[0].id;
    assert.equal(result.data.messages[0].unread,true);
    await request('/api/workspace/mail/meta',{id,read:true,favorite:true});
    result=await request('/api/workspace/mail');assert.equal(result.data.messages[0].favorite,true);assert.equal(result.data.messages[0].unread,false);
    const response=await fetch(origin+'/api/workspace/backup/download',{headers:{Cookie:'test-auth=1'}});
    assert.match(response.headers.get('content-type'),/ndjson/);assert.equal(response.headers.get('x-accel-buffering'),'no');
    const text=await response.text();assert.equal(workspace.parseBackup(text).messages.length,1);
    assert.equal((await workspace.restoreText(text)).restored,1);
    assert.equal((await workspace.restoreText(text)).restored,0);
    assert.equal((await request('/api/workspace/mail')).data.messages.length,1);
    assert.throws(()=>workspace.parseBackup(text.replace('/dev/ttyACM0','/dev/../../invalid')),/字段/);
    const created=await request('/api/workspace/uploads',{size:Buffer.byteLength(text)});const token=created.data.id;
    let put=await fetch(origin+'/api/workspace/uploads/'+token+'?offset=1',{method:'PUT',headers:{Cookie:'test-auth=1','Content-Type':'application/octet-stream'},body:text});assert.equal(put.status,400);
    put=await fetch(origin+'/api/workspace/uploads/'+token+'?offset=0',{method:'PUT',headers:{Cookie:'test-auth=1','Content-Type':'application/octet-stream'},body:text});assert.equal(put.status,200);
    assert.equal((await request('/api/workspace/restore',{upload:token})).data.restored,0);
    const before=(await request('/api/workspace/mail')).data.messages.length;
    await assert.rejects(workspace.restoreText('bad backup'),/JSON|Unexpected/);assert.equal((await request('/api/workspace/mail')).data.messages.length,before);
    const job=await request('/api/workspace/schedule',{port:'/dev/ttyACM0',phone:'+8613800000000',content:'定时测试',due:Date.now()+60000});assert.equal(job.data.job.state,'queued');
    await request('/api/workspace/schedule/'+job.data.job.id+'/cancel',{});assert.equal((await request('/api/workspace/mail')).data.schedules[0].state,'cancelled');
    assert.equal((await request('/api/workspace/schedule',{port:'/dev/ttyACM0',phone:'bad',content:'测试',due:Date.now()+60000})).status,400);
    assert.equal((await request('/api/workspace/schedule',{port:'/dev/ttyACM0',phone:'+8613800000000',content:'测试',due:Date.now()-1})).status,400);
    const scheduled=await request('/api/workspace/schedule',{port:'/dev/ttyACM0',phone:'+8613800000000',content:'测试到期',due:Date.now()+20});await new Promise(r=>setTimeout(r,30));await workspace.tick();await workspace.tick();
    const mailbox=(await request('/api/workspace/mail')).data;assert.equal(mailbox.schedules.find(j=>j.id===scheduled.data.job.id).state,'sent');assert.equal(mailbox.outbox.length,1);
    workspace.recordLog('/dev/ttyACM0','receive','OK');assert.equal((await request('/api/workspace/logs')).data.logs.length,1);
    const sim=await request('/api/workspace/sim/ttyACM0');assert.equal(sim.data.details.phone,'+8613800000000');assert.equal((await request('/api/workspace/mail')).data.messages[0].recipientPhone,'+8613800000000');const count=fixture.ctx.serial['/dev/ttyACM0'].commands.length;await request('/api/workspace/sim/ttyACM0');assert.equal(fixture.ctx.serial['/dev/ttyACM0'].commands.length,count);assert.equal(sim.data.details.imsi,'460001234567890');assert.equal(sim.data.details.fields.find(f=>f.key==='storage').value[0].total,50);
    assert.equal((await request('/api/workspace/sim/ttyACM0/number',{iccid:'wrong',phone:'+8613900000000'})).status,400);assert.equal((await request('/api/workspace/sim/ttyACM0/number',{iccid:fixture.modules['/dev/ttyACM0'].iccid,phone:'bad'})).status,400);assert.equal((await request('/api/workspace/sim/ttyACM0/number',{iccid:fixture.modules['/dev/ttyACM0'].iccid,phone:'+8613900000000'})).status,200);
    assert.equal(parseResponse('lteRegistration','+CEREG: 2,1,"abcd","1234"\r\nOK').meaning,'已注册（本地）');
    assert.equal(identifiers('8986001234567890123','460001234567890').imsi.mnc,'00');
    await request('/api/workspace/backup',{});const cache=(await request('/api/workspace/cache')).data.items;
    const currentLog=cache.find(i=>i.kind==='logs');assert.equal(currentLog.locked,true);
    const logClear=await request('/api/workspace/cache/clear',{items:[currentLog]});assert.equal(logClear.data.skipped.length,1);
    assert.equal((await request('/api/workspace/cache/clear',{items:[{kind:'backups',id:'../mail-state.enc'}]})).status,400);
    const backup=cache.find(i=>i.kind==='backups');assert.equal((await request('/api/workspace/cache/clear',{items:[{...backup,stamp:0}]})).data.skipped.length,1);
    assert.equal((await request('/api/workspace/cache/clear',{items:[backup]})).data.removed.length,1);
    assert.equal((await request('/api/workspace/device')).status,200);
    const stateFile=fs.readFileSync(path.join(fixture.root,'workspace-data/mail-state.enc'),'utf8');assert.ok(!stateFile.includes('测试来信'));
    const sendUpdate=async bundle=>{const text=JSON.stringify(bundle);const created=await request('/api/workspace/uploads',{size:Buffer.byteLength(text)});const id=created.data.id;await fetch(origin+'/api/workspace/uploads/'+id+'?offset=0',{method:'PUT',headers:{Cookie:'test-auth=1','Content-Type':'application/octet-stream'},body:text});return request('/api/workspace/upgrade/install',{source:'local',upload:id});};
    const crypto=require('crypto');
    const updateFile=(name,content)=>({path:name,content:Buffer.from(content).toString('base64'),sha256:crypto.createHash('sha256').update(content).digest('hex')});
    const html=fs.readFileSync(path.join(fixture.root,'public/index.html'),'utf8');const script=fs.readFileSync(path.join(fixture.root,'public/mail-workspace.js'),'utf8');
    const bundle={format:'lte-sms-ui-update',version:'3.0.1',files:[updateFile('public/mail-workspace.js',script),updateFile('public/index.html',html)]};
    assert.equal((await sendUpdate({...bundle,files:[...bundle.files,updateFile('../bad.js','evil')]})).status,400);
    assert.equal((await sendUpdate({...bundle,files:[{...bundle.files[0],sha256:'bad'},bundle.files[1]]})).status,400);
    assert.equal((await sendUpdate({...bundle,files:[updateFile('public/mail-workspace.js','const = broken;'),bundle.files[1]]})).status,400);
    assert.equal(fs.readFileSync(path.join(fixture.root,'public/mail-workspace.js'),'utf8'),script);
    assert.equal((await sendUpdate(bundle)).data.task.state,'completed');assert.equal((await request('/api/workspace/upgrade')).data.current,'3.0.1');
    const {createWorkspace}=require('../gateway-workspace');
    const statePath=path.join(fixture.root,'workspace-data/mail-state.enc');const state=JSON.parse(fixture.ctx.decrypt(fs.readFileSync(statePath,'utf8')));state.schedules[0].state='sending';fs.writeFileSync(statePath,fixture.ctx.encrypt(JSON.stringify(state)));
    const reloaded=createWorkspace(fixture.ctx);try{assert.equal(reloaded.allMail()[0].favorite,true);assert.equal(reloaded.allMail()[0].recipientPhone,'+8613800000000');fixture.modules['/dev/ttyACM0'].iccid='8986019999999999999';assert.equal(reloaded.allMail().find(m=>m.storageLocation==='sim').recipientPhone,'');const decoded=JSON.parse(fixture.ctx.decrypt(fs.readFileSync(statePath,'utf8')));assert.equal(decoded.schedules[0].state,'uncertain');}finally{reloaded.close();}
    console.log('Workspace API checks passed: auth, metadata, streaming backup, restore validation/deduplication, uploads, scheduler, SIM parsing, logs, cache protections, host telemetry.');
  } finally {await fixture.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
